### ISSUE TITLE
Error running pipeline stage TXTwoPoint. (16Jan20)

### ISSUE THREAD

**Issue by jecampagne** [LSSTDESC/TXPipe#60]
Hello,
As a newbie I'm currently trying to execute TXPipe on CORI.
```
git clone https://github.com/LSSTDESC/TXPipe
mkdir -p data/example/inputs
cd data/example/inputs
curl -O https://portal.nersc.gov/project/lsst/WeakLensing/shear_catalog.hdf5
curl -O https://portal.nersc.gov/project/lsst/WeakLensing/photometry_catalog.hdf5
curl -O https://portal.nersc.gov/project/lsst/WeakLensing/sample_cosmodc2_w10year_errors.dat
curl -O https://portal.nersc.gov/project/lsst/WeakLensing/cosmoDC2_trees_i25.3.npy
curl -O https://portal.nersc.gov/project/lsst/WeakLensing/exposures.hdf5
curl -O https://portal.nersc.gov/project/lsst/WeakLensing/star_catalog.hdf5
cd ../../..
shifter --image docker:joezuntz/txpipe bash
ceci examples/laptop.yml
```
Then it seems that there is an error. An idea?
Here is part of the output
```
 python3 -m txpipe TXTwoPoint   --shear_catalog=data/example/inputs/shear_catalog.hdf5   --tomography_catalog=data/example/outputs/tomography_catalog.hdf5   --photoz_stack=data/example/outputs/photoz_stack.hdf5   --random_cats=data/example/outputs/random_cats.hdf5   --config=examples/config.yml   --twopoint_data=data/example/outputs/twopoint_data.sacc 
Compiling command:

*************************************************
Error running pipeline stage TXTwoPoint.

Standard output and error streams below.

*************************************************

Standard output:
----------------

 python3 -m txpipe TXGammaTFieldCenters   --shear_catalog=data/example/inputs/shear_catalog.hdf5   --tomography_catalog=data/example/outputs/tomography_catalog.hdf5   --photoz_stack=data/example/outputs/photoz_stack.hdf5   --random_cats=data/example/outputs/random_cats.hdf5   --exposures=data/example/inputs/exposures.hdf5   --config=examples/config.yml   --gammat_field_center=data/example/outputs/gammat_field_center.sacc   --gammat_field_center_plot=data/example/outputs/gammat_field_center_plot.png 
/usr/local/lib/python3.6/dist-packages/ceci/stage.py:254: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  overall_config = yaml.load(open(self.get_input('config')))
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/global/u2/c/campagne/Work/TXPipe/txpipe/__main__.py", line 5, in <module>
    PipelineStage.main()
  File "/usr/local/lib/python3.6/dist-packages/ceci/stage.py", line 601, in main
    stage.execute(args)
  File "/usr/local/lib/python3.6/dist-packages/ceci/stage.py", line 671, in execute
    stage.run()
  File "/global/u2/c/campagne/Work/TXPipe/txpipe/twopoint.py", line 71, in run
    meta = self.calculate_metadata(data)
  File "/global/u2/c/campagne/Work/TXPipe/txpipe/twopoint.py", line 548, in calculate_metadata
    g1, g2, mask = self.get_m(data, i)
  File "/global/u2/c/campagne/Work/TXPipe/txpipe/twopoint.py", line 324, in get_m
    g1, g2 = apply_response(data['R_total'][i],data['mcal_g1'][mask],data['mcal_g2'][mask])
NameError: name 'apply_response' is not defined
--> executable follows <--
 python3 -m txpipe TXTwoPoint   --shear_catalog=data/example/inputs/shear_catalog.hdf5   --tomography_catalog=data/example/outputs/tomography_catalog.hdf5   --photoz_stack=data/example/outputs/photoz_stack.hdf5   --random_cats=data/example/outputs/random_cats.hdf5   --config=examples/config.yml   --twopoint_data=data/example/outputs/twopoint_data.sacc 
--> end executable <--

*************************************************

Standard error:
----------------

Executing stage: TXTwoPoint
Loading shear catalog columns: ['ra', 'dec', 'mcal_g1', 'mcal_g2', 'mcal_flags']
Loading ra
Loading dec
Loading mcal_g1
Loading mcal_g2
Loading mcal_flags
Loading random catalog columns: ['dec', 'e1', 'e2', 'ra', 'bin']
Running with 4 source bins and 1 lens bins
Pipeline failed.  No joy sparked.
Compiling command:
 python3 -m txpipe TXGammaTBrightStars   --shear_catalog=data/example/inputs/shear_catalog.hdf5   --tomography_catalog=data/example/outputs/tomography_catalog.hdf5   --photoz_stack=data/example/outputs/photoz_stack.hdf5   --random_cats=data/example/outputs/random_cats.hdf5   --star_catalog=data/example/inputs/star_catalog.hdf5   --config=examples/config.yml   --gammat_bright_stars=data/example/outputs/gammat_bright_stars.sacc   --gammat_bright_stars_plot=data/example/outputs/gammat_bright_stars_plot.png 
Compiling command:
 python3 -m txpipe TXGammaTDimStars   --shear_catalog=data/example/inputs/shear_catalog.hdf5   --tomography_catalog=data/example/outputs/tomography_catalog.hdf5   --photoz_stack=data/example/outputs/photoz_stack.hdf5   --random_cats=data/example/outputs/random_cats.hdf5   --star_catalog=data/example/inputs/star_catalog.hdf5   --config=examples/config.yml   --gammat_dim_stars=data/example/outputs/gammat_dim_stars.sacc   --gammat_dim_stars_plot=data/example/outputs/gammat_dim_stars_plot.png 
```

**Comment by joezuntz** [comment]
Fixed in master
